### ISSUE TITLE
I'm unable to pull chart

### ISSUE THREAD

**Issue by shrimpgo** [bman46/CTFd-Helm#4]
Hello!

I'm trying to use your chart for ctfd and when I follow the steps located in the README.md, it says: _Error: GET "https://ghcr.io/v2/bman46/ctfd/ctfd/tags/list": unable to retrieve credentials._ Where are these credentials? The command I'm using below:

`$ helm upgrade -i -f ctfd/config/values.yaml ctfd oci://ghcr.io/bman46/ctfd/ctfd`

Thanks

**Comment by bman46** [comment]
Try the following command. No authentication should be required. `helm install ctfd oci://ghcr.io/bman46/ctfd/ctfd --version 0.4.2`

**Comment by shrimpgo** [comment]
Thank you. It worked like a charm! One suggestion: maybe you have to add this information into README.md, what do you think?

**Comment by bman46** [comment]
Glad that it worked. I will add it to the readme as a short term fix. However, I think that there is another issue, potentially a bug/misconfiguration with GHCR or helm, that is the root cause of the issue and needs to be resolved.
