### ISSUE TITLE
Custom theming

### ISSUE THREAD

**Issue by osintalex** [bman46/CTFd-Helm#54]
This is amazingly helpful - your repo saved me ages of work. Thank you!!

I was wondering if you know an easy way to install a custom theme like this one with this setup? https://github.com/apogiatzis/ctfd-neon-theme

**Comment by bman46** [comment]
Thanks! The easiest way to do this will be to create a custom docker image that includes the theme. You can then override the docker image for this helm chart in the values file.

**Comment by osintalex** [comment]
Thanks, I actually ended up doing exactly that like 1h ago. Just cloned a theme in the first stage of the ctfd Dockerfile.

**Comment by bman46** [comment]
Nice!
